package io.github.yphyphyph.gogauge.ui

/**
 * UI strings — word-for-word port of app.js I18N tables (desktop).
 * Selected by [LangState] at runtime; Compose recomposes on language switch.
 */
open class Strings(
    val syncing: String,
    val themeDark: String,
    val themeLight: String,
    val refresh: String,
    val homeTitle: String,
    val today: String,
    val d7: String,
    val d30: String,
    val all: String,
    val overviewTitle: String,
    val followRange: String,
    val todayTrend: String,
    val hours24: String,
    val statsTitle: String,
    val tokenBreakdown: String,
    val modelUsage: String,
    val input: String,
    val output: String,
    val cost: String,
    val usageTrend: String,
    val usageRecords: String,
    val allModels: String,
    val recordsPage: String,
    val sessionUsage: String,
    val colSession: String,
    val colLastUsed: String,
    val colRequests: String,
    val unassigned: String,
    val colTime: String,
    val colModel: String,
    val colInput: String,
    val colOutput: String,
    val colReasoning: String,
    val colCacheRead: String,
    val colCost: String,
    val prev: String,
    val next: String,
    val settingsTitle: String,
    val setAccount: String,
    val setLoginState: String,
    val setWorkspace: String,
    val setLoginMethod: String,
    val loginMethodDesc: String,
    val relogin: String,
    val setLogout: String,
    val logoutDesc: String,
    val logout: String,
    val setAutoSync: String,
    val autoSync: String,
    val autoSyncDesc: String,
    val syncInterval: String,
    val syncIntervalDesc: String,
    val min1: String,
    val min5: String,
    val min15: String,
    val min30: String,
    val syncRange: String,
    val syncRangeDesc: String,
    val d30short: String,
    val d60: String,
    val d90: String,
    val d180: String,
    val fullSync: String,
    val fullSyncDesc: String,
    val startFullSync: String,
    val setAppearance: String,
    val theme: String,
    val themeDesc: String,
    val light: String,
    val dark: String,
    val currency: String,
    val currencyDesc: String,
    val language: String,
    val languageDesc: String,
    val setData: String,
    val dataDir: String,
    val syncInfo: String,
    val aboutTitle: String,
    val aboutIntro: String,
    val introText: String,
    val aboutFeatures: String,
    val feat1: String,
    val feat2: String,
    val feat3: String,
    val feat4: String,
    val feat5: String,
    val aboutLinks: String,
    val aboutThanks: String,
    val thanksText: String,
    val pageFoot: String,
    val welcomeDesc: String,
    val welcomeFeat1: String,
    val welcomeFeat2: String,
    val welcomeFeat3: String,
    val loginBtn: String,
    val loginNote: String,
    val quitApp: String,
    val rolling: String,
    val weekly: String,
    val monthly: String,
    val remaining: String,
    val used: String,
    val resetsIn: String,
    val hitRate: String,
    val hitAmount: String,
    val totalTokens: String,
    val totalRequests: String,
    val totalCost: String,
    val sessions: String,
    val hit: String,
    val miss: String,
    val pctOfInput: String,
    val inclCache: String,
    val currentRange: String,
    val avgPer: String,
    val perReq: String,
    val dedup: String,
    val noData: String,
    val loadFailed: String,
    val totalN: String,
    val items: String,
    val pageOf: String,
    val ofPages: String,
    val loggedIn: String,
    val notLoggedIn: String,
    val connected: String,
    val notConnected: String,
    val lastSync: String,
    val records: String,
    val updatedAt: String,
    val justNow: String,
    val minAgo: String,
    val hrAgo: String,
    val dayAgo: String,
    val never: String,
    val day: String,
    val hour: String,
    val minute: String,
    val soon: String,
    val dUnit: String,
    val hUnit: String,
    val mUnit: String,
    val confirm: String,
    val cancel: String,
    val ok: String,
    val fullSyncConfirm: String,
    val startSync: String,
    val reloginConfirm: String,
    val goLogin: String,
    val logoutConfirm: String,
    val quit: String,
    val setUsers: String,
    val addUser: String,
    val addUserTip: String,
    val userSwitchTip: String,
    val switchTo: String,
    val currentUserBadge: String,
    val renameBtn: String,
    val renameTitle: String,
    val deleteUser: String,
    val deleteTitle: String,
    val deleteUserConfirm: String,
    val userDeleted: String,
    val userRenamed: String,
    val switchedAccount: String,
    val noUsers: String,
    val manageUsers: String,
    val loggedOut: String,
    val logoutUserConfirm: String,
    val save: String,
    val quotaFail: String,
    val retryTip: String,
    val syncIntervalSet: String,
    val syncRangeUpdated: String,
    val trendHint: String,
    val totalTokenHint: String,
    val setUpdate: String,
    val currentVersion: String,
    val checkUpdate: String,
    val checkUpdateDesc: String,
    val checkUpdateBtn: String,
    val checkingUpdate: String,
    val updateFound: String,
    val updateNone: String,
    val updateFailed: String,
    val goDownload: String,
    val cacheWrite: String,
    val newCacheWrites: String,
    val loginTitle: String,
    // 账户总览面板 (desktop v2.1.0)
    val accountOverview: String,
    val costTrend7d: String,
    val todayTotalReq: String,
    val todayTotalTokens: String,
    val todayTotalInput: String,
    val todayTotalCost: String,
    val activeAccount: String,
    val quotaNotReady: String,
    val overviewPanel: String,
    val overviewPanelDesc: String,
)

object ZhStrings : Strings(
    syncing = "同步中", themeDark = "暗色", themeLight = "亮色", refresh = "刷新",
    homeTitle = "用量统计总览", today = "今天", d7 = "近7天", d30 = "近30天", all = "全部",
    overviewTitle = "用量概览", followRange = "数据跟随时间范围",
    todayTrend = "今日趋势", hours24 = "24 小时",
    statsTitle = "用量统计", tokenBreakdown = "Token 构成",
    modelUsage = "模型用量", input = "输入", output = "输出", cost = "成本",
    usageTrend = "用量趋势", usageRecords = "使用记录", allModels = "全部模型",
    recordsPage = "使用记录",
    sessionUsage = "会话用量", colSession = "会话", colLastUsed = "最后使用",
    colRequests = "请求/Token", unassigned = "未归属",
    colTime = "时间", colModel = "模型", colInput = "输入", colOutput = "输出",
    colReasoning = "推理", colCacheRead = "缓存读", colCost = "费用",
    prev = "上一页", next = "下一页",
    settingsTitle = "设置", setAccount = "OpenCode 账户", setLoginState = "登录状态",
    setWorkspace = "工作区", setLoginMethod = "登录方式",
    loginMethodDesc = "内置浏览器 (WebView2) 打开官方授权页，自动回填",
    relogin = "重新登录", setLogout = "退出登录",
    logoutDesc = "清除本地 token 与缓存数据", logout = "退出登录",
    setAutoSync = "自动同步", autoSync = "自动增量同步",
    autoSyncDesc = "按间隔拉取最新用量记录",
    syncInterval = "同步间隔", syncIntervalDesc = "多久自动同步一次",
    min1 = "1 分钟", min5 = "5 分钟", min15 = "15 分钟", min30 = "30 分钟",
    syncRange = "同步范围",
    syncRangeDesc = "本地保留与首次拉取的历史窗口；\"所有\"= 拉取全部（500 页保险）",
    d30short = "30天", d60 = "60天", d90 = "90天", d180 = "180天",
    fullSync = "立即全量同步", fullSyncDesc = "重新拉取历史记录，补全数据",
    startFullSync = "开始全量同步",
    setAppearance = "外观", theme = "主题", themeDesc = "亮色 / 深色，顶栏按钮快捷切换",
    light = "浅色", dark = "深色", currency = "默认货币",
    currencyDesc = "费用主显示货币（实时汇率）",
    language = "语言 / Language", languageDesc = "界面显示语言",
    setData = "数据", dataDir = "数据目录", syncInfo = "同步记录",
    aboutTitle = "关于", aboutIntro = "简介",
    introText = "是一款本地优先的 OpenCode Go 用量面板：配额窗口、Token 构成、模型排行与使用记录整理在同一处，打开即见。所有数据仅保存在本地，登录凭证只用于同步官方接口。",
    aboutFeatures = "功能",
    feat1 = "配额窗口实时监控（滚动 5 小时 / 每周 / 每月）",
    feat2 = "今日用量与 24 小时趋势",
    feat3 = "各模型 Token 消耗排行与用量趋势",
    feat4 = "详细使用记录分页浏览（10 条/页）",
    feat5 = "自动同步数据，无需手动刷新",
    aboutLinks = "链接", aboutThanks = "致谢", thanksText = "数据提供",
    pageFoot = "{version} · GoGauge · 数据仅保存在本地 · 数据提供 OpenCode",
    welcomeDesc = "本地优先的 OpenCode Go 用量仪表盘 — 配额窗口、Token 构成、模型排行、使用记录，打开即见。",
    welcomeFeat1 = "配额实时监控（5 小时 / 每周 / 每月）",
    welcomeFeat2 = "Token 全维度统计与 24 小时趋势",
    welcomeFeat3 = "数据仅保存在本机，安全私密",
    loginBtn = "立即登录",
    loginNote = "点击后将打开 OpenCode Go 官方授权页完成登录。",
    quitApp = "退出应用",
    rolling = "滚动用量", weekly = "每周用量", monthly = "每月用量",
    remaining = "剩余", used = "已用", resetsIn = "重置于",
    hitRate = "缓存命中率", hitAmount = "缓存命中量", totalTokens = "总 TOKEN 消耗",
    totalRequests = "总请求", totalCost = "总费用", sessions = "会话数",
    hit = "命中", miss = "未命中", pctOfInput = "占输入", inclCache = "含缓存命中",
    currentRange = "当前范围", avgPer = "均", perReq = "/次", dedup = "去重 sessionID",
    noData = "暂无记录", loadFailed = "加载失败", totalN = "共", items = "条",
    pageOf = "第", ofPages = "页",
    loggedIn = "已登录", notLoggedIn = "未登录", connected = "已连接", notConnected = "未连接",
    lastSync = "上次同步", records = "条记录", updatedAt = "更新于",
    justNow = "刚刚", minAgo = "分钟前", hrAgo = "小时前", dayAgo = "天前", never = "从未同步",
    day = "天", hour = "小时", minute = "分钟", soon = "即将重置",
    dUnit = "天", hUnit = "小时", mUnit = "分钟",
    confirm = "确认", cancel = "取消", ok = "确定",
    fullSyncConfirm = "将重新拉取历史记录（按同步范围），确定开始？", startSync = "开始同步",
    reloginConfirm = "将清除本地数据并打开官方授权页重新登录，确定？", goLogin = "去登录",
    logoutConfirm = "退出将清除本地 token 与全部缓存数据，确定退出？", quit = "退出",
    setUsers = "用户管理", addUser = "添加用户",
    addUserTip = "登录新的 OpenCode Go 账号并保存到本机",
    userSwitchTip = "切换用户", switchTo = "切换为当前",
    currentUserBadge = "当前", renameBtn = "重命名", renameTitle = "重命名用户",
    deleteUser = "删除", deleteTitle = "删除用户",
    deleteUserConfirm = "确定删除用户「{name}」？其本地用量数据与同步记录将一并清除，且无法恢复。",
    userDeleted = "用户已删除", userRenamed = "已重命名", switchedAccount = "已切换账号",
    noUsers = "暂无账号，点击「添加用户」登录",
    manageUsers = "管理用户", loggedOut = "已退出登录",
    logoutUserConfirm = "将退出「{name}」并清除其本地用量数据与同步记录，确定？",
    save = "保存",
    quotaFail = "配额获取失败", retryTip = "点击右上角刷新重试",
    syncIntervalSet = "同步间隔已设为", syncRangeUpdated = "同步范围已更新，下次全量同步生效",
    trendHint = "30 天", totalTokenHint = "含缓存命中",
    setUpdate = "软件更新", currentVersion = "当前版本",
    checkUpdate = "检查更新", checkUpdateDesc = "检查 GitHub 上是否有新版本",
    checkUpdateBtn = "检查更新", checkingUpdate = "检查中…",
    updateFound = "发现新版本", updateNone = "已是最新版本",
    updateFailed = "检查更新失败", goDownload = "前往下载",
    cacheWrite = "缓存写", newCacheWrites = "新写入缓存",
    loginTitle = "连接 OpenCode Go",
    accountOverview = "账户总览", costTrend7d = "7 日费用趋势对比",
    todayTotalReq = "今日总请求", todayTotalTokens = "今日总 TOKEN",
    todayTotalInput = "今日总输入", todayTotalCost = "今日总费用",
    activeAccount = "当前活跃", quotaNotReady = "配额获取中…",
    overviewPanel = "账户总览面板", overviewPanelDesc = "底部导航显示多账户总览入口，聚合展示各账户配额与用量",
)

object EnStrings : Strings(
    syncing = "Syncing", themeDark = "Dark", themeLight = "Light", refresh = "Refresh",
    homeTitle = "Usage Overview", today = "Today", d7 = "7 Days", d30 = "30 Days", all = "All",
    overviewTitle = "Usage Overview", followRange = "Follows selected range",
    todayTrend = "Today's Trend", hours24 = "24 Hours",
    statsTitle = "Usage Stats", tokenBreakdown = "Token Breakdown",
    modelUsage = "Model Usage", input = "Input", output = "Output", cost = "Cost",
    usageTrend = "Usage Trend", usageRecords = "Usage Records", allModels = "All Models",
    recordsPage = "Records",
    sessionUsage = "Session Usage", colSession = "Session", colLastUsed = "Last Used",
    colRequests = "Requests/Token", unassigned = "Unassigned",
    colTime = "Time", colModel = "Model", colInput = "Input", colOutput = "Output",
    colReasoning = "Reasoning", colCacheRead = "Cache Read", colCost = "Cost",
    prev = "Prev", next = "Next",
    settingsTitle = "Settings", setAccount = "OpenCode Account", setLoginState = "Login Status",
    setWorkspace = "Workspace", setLoginMethod = "Login Method",
    loginMethodDesc = "Built-in browser (WebView2) opens the official auth page and auto-fills",
    relogin = "Re-login", setLogout = "Logout",
    logoutDesc = "Clear local token and cached data", logout = "Logout",
    setAutoSync = "Auto Sync", autoSync = "Auto incremental sync",
    autoSyncDesc = "Fetch latest usage records at interval",
    syncInterval = "Sync Interval", syncIntervalDesc = "How often to auto sync",
    min1 = "1 min", min5 = "5 min", min15 = "15 min", min30 = "30 min",
    syncRange = "Sync Range",
    syncRangeDesc = "Local history window for initial fetch; \"All\" = fetch everything (500-page safety cap)",
    d30short = "30d", d60 = "60d", d90 = "90d", d180 = "180d",
    fullSync = "Full Sync Now", fullSyncDesc = "Re-fetch history records to fill gaps",
    startFullSync = "Start Full Sync",
    setAppearance = "Appearance", theme = "Theme", themeDesc = "Light / Dark, quick toggle in top bar",
    light = "Light", dark = "Dark", currency = "Currency",
    currencyDesc = "Primary currency for costs (live FX rate)",
    language = "Language", languageDesc = "Interface language",
    setData = "Data", dataDir = "Data Directory", syncInfo = "Sync History",
    aboutTitle = "About", aboutIntro = "Intro",
    introText = "is a local-first OpenCode Go usage dashboard: quota windows, token breakdown, model ranking and usage records in one place. All data stays on your machine; credentials are only used to sync official APIs.",
    aboutFeatures = "Features",
    feat1 = "Quota window monitoring (5h rolling / weekly / monthly)",
    feat2 = "Today's usage with 24-hour trend",
    feat3 = "Per-model token ranking and usage trend",
    feat4 = "Paginated usage records (10 per page)",
    feat5 = "Auto sync — no manual refresh needed",
    aboutLinks = "Links", aboutThanks = "Thanks", thanksText = "Data provided by",
    pageFoot = "{version} · GoGauge · Local-only data · Data by OpenCode",
    welcomeDesc = "A local-first OpenCode Go usage dashboard — quota windows, token breakdown, model ranking and usage records in one place.",
    welcomeFeat1 = "Real-time quota monitoring (5h / weekly / monthly)",
    welcomeFeat2 = "Full token stats with 24-hour trend",
    welcomeFeat3 = "All data stays on your machine — private & safe",
    loginBtn = "Login Now",
    loginNote = "Clicking opens the official OpenCode Go authorization page.",
    quitApp = "Quit App",
    rolling = "Rolling Usage", weekly = "Weekly Usage", monthly = "Monthly Usage",
    remaining = "Remaining", used = "Used", resetsIn = "Resets in",
    hitRate = "Cache Hit Rate", hitAmount = "Cache Hits", totalTokens = "Total Tokens",
    totalRequests = "Requests", totalCost = "Total Cost", sessions = "Sessions",
    hit = "hit", miss = "missed", pctOfInput = "of input", inclCache = "incl. cache hits",
    currentRange = "current range", avgPer = "avg", perReq = "/req", dedup = "dedup sessionID",
    noData = "No records", loadFailed = "Failed to load", totalN = "Total", items = "records",
    pageOf = "Page", ofPages = "of",
    loggedIn = "Logged in", notLoggedIn = "Not logged in", connected = "Connected", notConnected = "Not connected",
    lastSync = "Last sync", records = "records", updatedAt = "Updated",
    justNow = "just now", minAgo = "min ago", hrAgo = "hr ago", dayAgo = "d ago", never = "Never synced",
    day = "d", hour = "h", minute = "m", soon = "resets soon",
    dUnit = "d", hUnit = "h", mUnit = "m",
    confirm = "Confirm", cancel = "Cancel", ok = "OK",
    fullSyncConfirm = "This will re-fetch all history records (per sync range). Continue?", startSync = "Start Sync",
    reloginConfirm = "This will clear local data and open the auth page. Continue?", goLogin = "Go Login",
    logoutConfirm = "This will clear local token and all cached data. Continue?", quit = "Logout",
    setUsers = "User Management", addUser = "Add User",
    addUserTip = "Sign in with another OpenCode Go account",
    userSwitchTip = "Switch user", switchTo = "Make Active",
    currentUserBadge = "Active", renameBtn = "Rename", renameTitle = "Rename User",
    deleteUser = "Delete", deleteTitle = "Delete User",
    deleteUserConfirm = "Delete user \"{name}\"? Their local usage data and sync history will be removed permanently.",
    userDeleted = "User deleted", userRenamed = "Renamed", switchedAccount = "Account switched",
    noUsers = "No accounts yet — tap \"Add User\" to sign in",
    manageUsers = "Manage users", loggedOut = "Signed out",
    logoutUserConfirm = "Sign out \"{name}\" and remove their local usage data and sync history?",
    save = "Save",
    quotaFail = "Quota fetch failed", retryTip = "Click refresh in top bar to retry",
    syncIntervalSet = "Sync interval set to", syncRangeUpdated = "Sync range updated, takes effect on next full sync",
    trendHint = "30 days", totalTokenHint = "incl. cache hits",
    setUpdate = "Software Update", currentVersion = "Current Version",
    checkUpdate = "Check Updates", checkUpdateDesc = "Check GitHub for new versions",
    checkUpdateBtn = "Check Updates", checkingUpdate = "Checking…",
    updateFound = "New Version Available", updateNone = "You're up to date",
    updateFailed = "Check failed", goDownload = "Go to Download",
    cacheWrite = "Cache Write", newCacheWrites = "new cache writes",
    loginTitle = "Connect OpenCode Go",
    accountOverview = "Accounts Overview", costTrend7d = "7-Day Cost Trend",
    todayTotalReq = "Today Requests", todayTotalTokens = "Today Tokens",
    todayTotalInput = "Today Input", todayTotalCost = "Today Cost",
    activeAccount = "Active", quotaNotReady = "Fetching quota…",
    overviewPanel = "Accounts Panel", overviewPanelDesc = "Show multi-account overview entry in bottom navigation",
)
